name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily at midnight
  workflow_dispatch:  # Allows you to manually run this action from GitHub Actions tab

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push Snake to repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          file: dist/snake.svg
